### ISSUE TITLE
How do you start a local network with this project? 

### ISSUE THREAD

**Issue by jaybxyz** [larry0x/simapp#3]
While I was experimenting with your [implementation of abstract account](https://github.com/larry0x/abstract-account), I came across this project and began to wonder about how to start a local network with this minimalistic project. I acknolwedge that there are multiple ways to start a local network but i am attempting to utilize `simd` commands as i believe you aren't utilizing the [Ignite CLI](https://github.com/ignite/cli) (i don't see `config.yml` file in the repository).

Also, i notice that it doesn't appear to support the essential genesis commands because the [genesisCommand](https://github.com/larry0x/simapp/blob/main/cmd/simd/main.go#L172) in `cmd/simd/main.go` does not add commands, such as `GenTxCmd`, `MigrateGenesisCmd`, `CollectGenTxsCmd`.

When you have a chance, can you please share the approach you take to start a local network?

**Comment by jaybxyz** [comment]
On top of that, I've tried to register the missing genesis commands as the way Cosmos SDK v0.47.2 does in its `simapp` and i am encountering the following error when trying to generate a genesis transaction that creates a validator with a self-delegation, that is signed by the key in the Keyring referenced by a given name. I believe it is probably due to the `poa` module that is being used in this project.

```
panic: interface conversion: module.AppModuleBasic is nil, not genutil.AppModuleBasic
```

**Comment by Reecepbcups** [comment]
I had a PR https://github.com/larry0x/simapp/pull/2 which make this easy if on a unix system

unsure if it really fits this repo though.

**Comment by jaybxyz** [comment]
@Reecepbcups Are you sure the script works on a unix system? Because i see that the `test_node` script executes `gentx`, `collect-gentxs`, and `validate-genesis` commands which this project does not support.

**Comment by jaybxyz** [comment]
@larry0x Thanks for your quick reply. 

> check out this document: https://github.com/larry0x/workshops/blob/main/how-to-run-a-validator/README.md

The point that I am having a trouble to understand is that this project `simapp` does not support `gentx` and `collect-gentxs` commands when I build the binary `simd`. See [this genesisCommand function](https://github.com/larry0x/simapp/blob/main/cmd/simd/main.go#L172). It only adds `ValidateGenesisCmd` and `AddGenesisAccountCmd`. Therefore, running commands that I use for other chains don't seem to work.

> This simapp uses a simple proof-of-authority (PoA) module instead of proof-of-stake as in the original simapp (https://github.com/cosmos/cosmos-sdk/tree/main/simapp) which the document/video uses, so the process is a bit different.

Like you said, I am thinking that the process is a bit different since it uses a simple PoA. It would be great if you could provide a script or prepared commands that you use to run a local network with this simapp.

**Comment by larry0x** [comment]
@jaybxyz After you run `simd init`, take a look at the following section of the `genesis.toml`:

```json
{
  "app_state": {
    "poa": {
      "validators": []
    }
  }
}
```

This is the PoA module's genesis state. Currently the list of validators is empty.

Take a look at the `priv_validator_key.json` file:

```json
{
  "address": "...",
  "pub_key": {
    "type": "tendermint/PubKeyEd25519",
    "value": "..."
  },
  "priv_key": {
    "type": "tendermint/PrivKeyEd25519",
    "value": "..."
  }
}
```

This file contains your node's Tendermint consensus key.

What you need to do is to edit the `genesis.json` like this:

```json
{
  "app_state": {
    "poa": {
      "validators": [
        {
          "pub_key": {
            "ed25519": "..."
          },
          "power": 1
        }
      ]
    }
  }
}
```

By copying the _public_ key in `priv_validator_key.json` over.

**Comment by larry0x** [comment]
Here is the complete `genesis.json` I used for the account abstraction project: https://gist.github.com/larry0x/666074088d54dabd256aad35557e602c

This uses the fork of simapp found here: https://github.com/larry0x/abstract-account/tree/main/simapp

**Comment by jaybxyz** [comment]
@larry0x Thanks a lot for your detailed explanation. That works perfectly!
